pipeline {
    agent { label "built-in" }
    stages{
        stage("Resource"){
            steps {
                checkout scmGit(branches: [[name: '*/master']], extensions: [], 
                userRemoteConfigs: [[url: 'https://github.com/leangsengk90/employee-ui.git']])
            }
        }
        stage("Build"){
            steps {
                sh """
                    docker ps
                """
            }  
        }
    }

}
