pipeline {
    agent { label "built-in"}

    environment {
        PROJECT_PATH = "employee-ui"
    }

    stages{
        stage("Resource"){
            steps {
                dir("$WORKSPACE/$PROJECT_PATH"){
                    checkout scmGit(branches: [[name: '*/master']], extensions: [], 
                    userRemoteConfigs: [[url: 'https://github.com/leangsengk90/employee-ui.git']])
                }
            }
        }

        stage("Configuration"){
            steps {
                sh """
                    cp pipelines/Dockerfile $WORKSPACE/$PROJECT_PATH
                """
            }
        }

        stage("Build"){
            steps {
                dir("$WORKSPACE/$PROJECT_PATH"){
                    withCredentials([usernamePassword(credentialsId: 'docker-registry', 
                        passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME')]) {
                        sh """
                            docker login -u $USERNAME -p $USERNAME
                            docker build -t xeng/employee-ui:$BUILD_NUMBER -f Dockerfile .
                            docker push xeng/employee-ui:$BUILD_NUMBER
                        """
                    }
                    
                }
            }
        }
    }

}
